enum QueueMessageOperation {
  UPSERT = 'UPSERT',
  DELETE = 'DELETE',
  ENROLLMENT_REQUEST = 'ENROLLMENT_REQUEST',
  ENROLLMENT_CANCEL_REQUEST = 'ENROLLMENT_CANCEL_REQUEST',
  ENROLLMENT_STATUS_UPDATE = 'ENROLLMENT_STATUS_UPDATE',
}

export { QueueMessageOperation };
