version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - /tmp/lib/zookeeper/data:/data
      - /tmp/log/zookeeper/datalog:/datalog
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /tmp/log/kafka/kafka-logs-1:/kafka/kafka-logs-1
