export const PERMISSIONS = Object.freeze({
  USERS: {
    VIEW: 'USERS.VIEW',
    CREATE: 'USERS.CREATE',
    EDIT: 'USERS.EDIT',
    VIEW_SCREEN: 'USERS.VIEW_SCREEN',
  },

  ROLES: {
    VIEW: 'ROLES.VIEW',
    CREATE: 'ROLES.CREATE',
    EDIT: 'ROLES.EDIT',
    DELETE: 'ROLES.DELETE',
    SALESMAN: 'ROLES.SALESMAN',
    INTERVIEWER: 'ROLES.INTERVIEWER',
    VIEW_SCREEN: 'ROLES.VIEW_SCREEN',
    RECEPTIONIST: 'ROLES.RECEPTIONIST',
    ADMIN: 'ROLES.ADMIN',
    GENERALMANAGER: 'ROLES.GENERALMANAGER',
    SALE_HO: 'ROLES.SALE_HO',
  },

  SALESMAN: {
    VIEW: 'SALESMAN.VIEW',
    VIEW_SCREEN: 'SALESMAN.VIEW_SCREEN',
  },

  INTERVIEWER: {
    VIEW: 'INTERVIEWER.VIEW',
    VIEW_SCREEN: 'INTERVIEWER.VIEW_SCREEN',
  },

  RECEPTIONIST: {
    VIEW: 'RECEPTIONIST.VIEW',
    VIEW_SCREEN: 'RECEPTIONIST.VIEW_SCREEN',
  },
  GENERALMANAGER: {
    VIEW: 'GENERALMANAGER.VIEW',
    VIEW_SCREEN: 'GENERALMANAGER.VIEW_SCREEN',
  },
});
