export const PERMISSIONS = Object.freeze({
  USERS: {
    VIEW: 'USERS.VIEW',
    CREATE: 'USERS.CREATE',
    EDIT: 'USERS.EDIT',
    VIEW_SCREEN: 'USERS.VIEW_SCREEN',
  },

  CAMPAIGNS: {
    VIEW: 'CAMPAIGNS.VIEW',
    VIEW_SCREEN: 'CAMPAIGNS.VIEW_SCREEN',
    CREATE: 'CAMPAIGNS.CREATE',
    EDIT: 'CAMPAIGNS.EDIT',
    DELETE: 'CAMPAIGNS.DELETE',
  },

  CENTRES: {
    VIEW: 'CENTRES.VIEW',
    VIEW_SCREEN: 'CENTRES.VIEW_SCREEN',
    CREATE: 'CENTRES.CREATE',
    EDIT: 'CENTRES.EDIT',
    DELETE: 'CENTRES.DELETE',
  },

  CONTACTS: {
    VIEW: 'CONTACTS.VIEW',
    CREATE: 'CONTACTS.CREATE',
    EDIT: 'CONTACTS.EDIT',
    DELETE: 'CONTACTS.DELETE',
    VIEW_ALL: 'CONTACTS.VIEW_ALL',
    VIEW_SALEMAN: 'CONTACTS.VIEW_SALEMAN',
    VIEW_CENTER: 'CONTACTS.VIEW_CENTER',
    ASSIGN: 'CONTACTS.ASSIGN',
    CENTRE: 'CONTACTS.CENTRE',
  },

  DEFAULT_TASKS: {
    VIEW: 'DEFAULT_TASKS.VIEW',
    VIEW_SCREEN: 'DEFAULT_TASKS.VIEW_SCREEN',
    CREATE: 'DEFAULT_TASKS.CREATE',
    EDIT: 'DEFAULT_TASKS.EDIT',
    DELETE: 'DEFAULT_TASKS.DELETE',
  },

  LEAD_APPOINTMENTS: {
    VIEW: 'LEAD_APPOINTMENTS.VIEW',
    CREATE: 'LEAD_APPOINTMENTS.CREATE',
    EDIT: 'LEAD_APPOINTMENTS.EDIT',
    DELETE: 'LEAD_APPOINTMENTS.DELETE',
  },

  LEAD_PO: {
    VIEW: 'LEAD_PO.VIEW',
    CREATE: 'LEAD_PO.CREATE',
    EDIT: 'LEAD_PO.EDIT',
    DELETE: 'LEAD_PO.DELETE',
  },

  LEAD_TASKS: {
    VIEW: 'LEAD_TASKS.VIEW',
    CREATE: 'LEAD_TASKS.CREATE',
    EDIT: 'LEAD_TASKS.EDIT',
    DELETE: 'LEAD_TASKS.DELETE',
  },

  LEADS: {
    VIEW: 'LEADS.VIEW',
    CREATE: 'LEADS.CREATE',
    EDIT: 'LEADS.EDIT',
    ASSIGN: 'LEADS.ASSIGN',
    CENTRE: 'LEADS.CENTRE',
    DELETE: 'LEADS.DELETE',
    VIEW_PIPELINE_SCREEN: 'LEADS.VIEW_PIPELINE_SCREEN',
    VIEW_UNASSIGNED_SCREEN: 'LEADS.VIEW_UNASSIGNED_SCREEN',
    VIEW_SCREEN: 'LEADS.VIEW_SCREEN',
    VIEW_ALL: 'LEADS.VIEW_ALL',
    VIEW_SALEMAN: 'LEADS.VIEW_SALEMAN',
    VIEW_CENTER: 'LEADS.VIEW_CENTER',
    // VIEW PERMISSION BY BUSSINESS ROLES
    VIEW_SALESMAN: 'LEADS_VIEW.BY_OWNER.WITHIN_CENTRE',
    VIEW_GM: 'LEADS_VIEW.BY_ANY.WITHIN_CENTRE',
    VIEW_HO: 'LEADS_VIEW.BY_ANY.WITHIN_ANY',
    VIEW_ACCOUNTANT: 'LEADS_VIEW.BY_ANY.WITHIN_ANY',
    VIEW_ADMIN: 'LEADS_VIEW.BY_ANY.WITHIN_ANY',
  },

  LISTS: {
    VIEW: 'LISTS.VIEW',
    CREATE: 'LISTS.CREATE',
    EDIT: 'LISTS.EDIT',
    DELETE: 'LISTS.DELETE',
  },

  PRODUCT_COMBOS: {
    VIEW: 'PRODUCT_COMBOS.VIEW',
    VIEW_SCREEN: 'PRODUCT_COMBOS.VIEW_SCREEN',
    CREATE: 'PRODUCT_COMBOS.CREATE',
    EDIT: 'PRODUCT_COMBOS.EDIT',
    DELETE: 'PRODUCT_COMBOS.DELETE',
  },

  PRODUCT_COURSES: {
    VIEW: 'PRODUCT_COURSES.VIEW',
    VIEW_SCREEN: 'PRODUCT_COURSES.VIEW_SCREEN',
    CREATE: 'PRODUCT_COURSES.CREATE',
    EDIT: 'PRODUCT_COURSES.EDIT',
    DELETE: 'PRODUCT_COURSES.DELETE',
  },

  SYSTEM_CONFIGS: {
    VIEW: 'SYSTEM_CONFIGS.VIEW',
    CREATE: 'SYSTEM_CONFIGS.CREATE',
    EDIT: 'SYSTEM_CONFIGS.EDIT',
    DELETE: 'SYSTEM_CONFIGS.DELETE',
  },

  LEAD_CONVERSATIONS: {
    VIEW: 'LEAD_CONVERSATIONS.VIEW',
    CREATE: 'LEAD_CONVERSATIONS.CREATE',
    EDIT: 'LEAD_CONVERSATIONS.EDIT',
    DELETE: 'LEAD_CONVERSATIONS.DELETE',
  },

  LEAD_MESSAGE_DETAILS: {
    VIEW: 'LEAD_MESSAGE_DETAILS.VIEW',
    CREATE: 'LEAD_MESSAGE_DETAILS.CREATE',
    EDIT: 'LEAD_MESSAGE_DETAILS.EDIT',
    DELETE: 'LEAD_MESSAGE_DETAILS.DELETE',
  },

  LEAD_ATTACHMENTS: {
    VIEW: 'LEAD_ATTACHMENTS.VIEW',
    CREATE: 'LEAD_ATTACHMENTS.CREATE',
    EDIT: 'LEAD_ATTACHMENTS.EDIT',
    DELETE: 'LEAD_ATTACHMENTS.DELETE',
  },

  LEAD_PAYMENT_TRANSACTION: {
    VIEW: 'LEAD_PAYMENT_TRANSACTION.VIEW',
    CREATE: 'LEAD_PAYMENT_TRANSACTION.CREATE',
    EDIT: 'LEAD_PAYMENT_TRANSACTION.EDIT',
    DELETE: 'LEAD_PAYMENT_TRANSACTION.DELETE',
  },

  LEAD_NOTE: {
    VIEW: 'LEAD_NOTE.VIEW',
    CREATE: 'LEAD_NOTE.CREATE',
    EDIT: 'LEAD_NOTE.EDIT',
    DELETE: 'LEAD_NOTE.DELETE',
  },

  LEAD_OWNER: {
    SALESMAN: 'LEAD_OWNER.GIVE.WITHIN_CENTRE.TO_ANY_ROLE.TO_WITHIN_CENTRE', // Salesman, must be the owner
    SALESMAN_TO_THEMSELF: 'LEAD_OWNER.ASSIGN.WITHIN_CENTRE.TO_SELF.TO_WITHIN_ANY',
    GM_WITHIN_CENTRE: 'LEAD_OWNER.OVERRIDE.WITHIN_CENTRE.TO_ANY_ROLE.TO_WITHIN_CENTRE', // GM
    GM_TO_GM: 'LEAD_OWNER.OVERRIDE.WITHIN_CENTRE.TO_GM_ROLE.TO_WITHIN_ANY', // GM
    SALE_HO_TO_GM: 'LEAD_OWNER.GIVE.WITHIN_ANY.TO_GM_ROLE.TO_WITHIN_ANY', // Sales HO, must be owner
    SALE_HO_TO_SALE_HO: 'LEAD_OWNER.GIVE.WITHIN_ANY.TO_HO_ROLE.TO_WITHIN_ANY', // Sales HO, must be owner
    SALE_HO_ASSIGN: 'LEAD_OWNER.ASSIGN.WITHIN_ANY.TO_GM_ROLE.TO_WITHIN_ANY',
    SALE_HO_ASSIGN_TO_SALE_HO: 'LEAD_OWNER.ASSIGN.WITHIN_ANY.TO_HO_ROLE.TO_WITHIN_ANY', // Sales HO, when contact is unwoned
    ADMIN: 'LEAD_OWNER.OVERRIDE.WITHIN_ANY.TO_ANY_ROLE.TO_WITHIN_ANY', // Admin
  },

  LEAD_PAYMENT: {
    CREATE: 'LEAD_PAYMENT.CREATE',
    VIEW: 'LEAD_PAYMENT.VIEW',
    EDIT: 'LEAD_PAYMENT.EDIT',
    DELETE: 'LEAD_PAYMENT.DELETE',
  },

  LEAD_REFUND: {
    CREATE: 'LEAD_REFUND.CREATE',
    VIEW: 'LEAD_REFUND.VIEW',
    EDIT: 'LEAD_REFUND.EDIT',
    DELETE: 'LEAD_REFUND.DELETE',
  },

  LEAD_ORDER: {
    ADD_ITEM_WHEN_COMPLETE: 'LEAD_ORDER.ADD_ITEM_WHEN_COMPLETE',
  },

  EMAIL_TEMPLATES: {
    VIEW: 'EMAIL_TEMPLATES.VIEW',
    VIEW_SCREEN: 'EMAIL_TEMPLATES.VIEW_SCREEN',
    CREATE: 'EMAIL_TEMPLATES.CREATE',
    EDIT: 'EMAIL_TEMPLATES.EDIT',
    DELETE: 'EMAIL_TEMPLATES.DELETE',
  },

  LEAD_NOTIFICATIONS: {
    VIEW: 'LEAD_NOTIFICATIONS.VIEW',
    CREATE: 'LEAD_NOTIFICATIONS.CREATE',
    EDIT: 'LEAD_NOTIFICATIONS.EDIT',
    DELETE: 'LEAD_NOTIFICATIONS.DELETE',
    VIEW_ALL_NOTIFICATIONS: 'LEAD_NOTIFICATIONS.VIEW_ALL_NOTIFICATIONS',
  },

  CLASS: {
    VIEW: 'CLASS.VIEW',
    VIEW_SCREEN: 'CLASS.VIEW_SCREEN',
    CREATE: 'CLASS.CREATE',
    EDIT: 'CLASS.EDIT',
    DELETE: 'CLASS.DELETE',
    VIEW_CENTER: 'CLASS.VIEW_CENTER',
  },

  PROSPECTING_LIST: {
    VIEW: 'PROSPECTING_LIST.VIEW',
    CREATE: 'PROSPECTING_LIST.CREATE',
    EDIT: 'PROSPECTING_LIST.EDIT',
    DELETE: 'PROSPECTING_LIST.DELETE',
    VIEW_ALL: 'PROSPECTING_LIST.VIEW_ALL',
    VIEW_ALL_SCREEN: 'PROSPECTING_LIST.VIEW_ALL_SCREEN',
  },

  DEMO: {
    VIEW: 'DEMO.VIEW',
  },

  SETTING: {
    VIEW: 'SETTING.VIEW',
  },

  PAGES: {
    VIEW: 'PAGES.VIEW',
    VIEW_FB: 'PAGES.VIEW_FB',
    VIEW_MAIL: 'PAGES.VIEW_MAIL',
  },

  ADS: {
    VIEW: 'ADS.VIEW',
  },

  ROLES: {
    VIEW: 'ROLES.VIEW',
    CREATE: 'ROLES.CREATE',
    EDIT: 'ROLES.EDIT',
    DELETE: 'ROLES.DELETE',
    SALESMAN: 'ROLES.SALESMAN',
    INTERVIEWER: 'ROLES.INTERVIEWER',
    VIEW_SCREEN: 'ROLES.VIEW_SCREEN',
    RECEPTIONIST: 'ROLES.RECEPTIONIST',
    ACCOUNTANT: 'ROLES.ACCOUNTANT',
    GENERALMANAGER: 'ROLES.GENERALMANAGER',
    ADMIN: 'ROLES.ADMIN',
    SALE_HO: 'ROLES.SALE_HO',
  },

  RECEPTIONIST: {
    VIEW: 'RECEPTIONIST.VIEW',
    VIEW_SCREEN: 'RECEPTIONIST.VIEW_SCREEN',
  },

  GENERALMANAGER: {
    VIEW: 'GENERALMANAGER.VIEW',
    VIEW_SCREEN: 'GENERALMANAGER.VIEW_SCREEN',
  },

  SALESMAN: {
    VIEW: 'SALESMAN.VIEW',
    VIEW_SCREEN: 'SALESMAN.VIEW_SCREEN',
  },

  INTERVIEWER: {
    VIEW: 'INTERVIEWER.VIEW',
    VIEW_SCREEN: 'INTERVIEWER.VIEW_SCREEN',
  },

  PRODUCTS: {
    VIEW: 'PRODUCTS.VIEW',
    CREATE: 'PRODUCTS.CREATE',
    EDIT: 'PRODUCTS.EDIT',
    VIEW_SCREEN: 'PRODUCTS.VIEW_SCREEN',
  },

  LMS_COURSES: {
    VIEW: 'LMS_COURSES.VIEW',
    VIEW_SCREEN: 'LMS_COURSES.VIEW_SCREEN',
  },

  LMS_CLASSES: {
    VIEW: 'LMS_CLASSES.VIEW',
  },

  LMS_CATEGORIES: {
    VIEW: 'LMS_CATEGORIES.VIEW',
  },
});
